from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class NewsRiskResearchPaths:
    output_dir: Path
    dataset_csv_path: Path
    coverage_json_path: Path
    leakage_json_path: Path
    metrics_json_path: Path
    portfolio_json_path: Path
    accounting_json_path: Path
    accounting_audit_json_path: Path
    equity_curve_csv_path: Path
    drawdown_curve_csv_path: Path
    trade_ledger_csv_path: Path
    daily_equity_price_only_csv_path: Path
    daily_equity_news_cash_csv_path: Path
    daily_equity_news_replacement_csv_path: Path
    daily_equity_news_reduced_size_csv_path: Path
    open_trade_portfolio_json_path: Path
    replay_risk_metrics_json_path: Path
    action_attribution_json_path: Path
    score_direction_audit_json_path: Path
    news_score_deciles_csv_path: Path
    corrected_news_score_deciles_csv_path: Path
    decile_join_audit_json_path: Path
    decile_trade_reconciliation_json_path: Path
    news_score_direction_report_json_path: Path
    news_score_direction_summary_md_path: Path
    replay_action_attribution_json_path: Path
    event_category_analysis_json_path: Path
    contrarian_strategy_comparison_json_path: Path
    contrarian_trade_ledger_csv_path: Path
    price_stabilisation_comparison_json_path: Path
    resilience_filter_analysis_json_path: Path
    extreme_event_archive_csv_path: Path
    extreme_event_memory_report_json_path: Path
    cost_scenario_comparison_json_path: Path
    chronological_split_manifest_json_path: Path
    experiment_registry_jsonl_path: Path
    contrarian_grid_results_csv_path: Path
    contrarian_grid_selection_json_path: Path
    contrarian_fold_results_csv_path: Path
    contrarian_parameter_stability_json_path: Path
    contrarian_frozen_config_json_path: Path
    contrarian_holdout_report_json_path: Path
    contrarian_holdout_trade_ledger_csv_path: Path
    contrarian_holdout_equity_csv_path: Path
    contrarian_holdout_comparison_md_path: Path
    contrarian_walk_forward_folds_csv_path: Path
    contrarian_walk_forward_summary_json_path: Path
    contrarian_chronological_validation_plan_json_path: Path
    contrarian_chronological_periods_csv_path: Path
    contrarian_walk_forward_validation_report_json_path: Path
    contrarian_placebo_permutation_report_json_path: Path
    contrarian_placebo_permutation_results_csv_path: Path
    contrarian_matched_control_report_json_path: Path
    contrarian_matched_control_results_csv_path: Path
    contrarian_profit_concentration_report_json_path: Path
    contrarian_trade_fragility_by_symbol_csv_path: Path
    contrarian_trade_fragility_by_year_csv_path: Path
    contrarian_top_trade_removal_csv_path: Path
    contrarian_year_regime_report_json_path: Path
    contrarian_year_regime_results_csv_path: Path
    contrarian_year_regime_examples_csv_path: Path
    contrarian_symbol_year_ablation_report_json_path: Path
    contrarian_without_top_symbols_csv_path: Path
    contrarian_without_top_years_csv_path: Path
    contrarian_cost_slippage_robustness_report_json_path: Path
    contrarian_cost_slippage_robustness_csv_path: Path
    contrarian_data_validity_audit_json_path: Path
    intraday_5min_expansion_plan_json_path: Path
    contrarian_placebo_results_csv_path: Path
    contrarian_placebo_summary_json_path: Path
    contrarian_matched_controls_json_path: Path
    contrarian_contribution_by_year_csv_path: Path
    contrarian_contribution_by_symbol_csv_path: Path
    contrarian_concentration_report_json_path: Path
    universe_survivorship_audit_json_path: Path
    universe_membership_by_date_csv_path: Path
    corporate_action_audit_json_path: Path
    missing_news_bias_report_json_path: Path
    covered_vs_uncovered_candidates_csv_path: Path
    text_model_readiness_json_path: Path
    validation_stage_placeholders_json_path: Path
    parallel_execution_report_json_path: Path
    replay_assumptions_json_path: Path
    replay_data_audit_json_path: Path
    artifact_manifest_json_path: Path
    artifact_validation_report_json_path: Path
    news_validation_workflow_map_json_path: Path
    validation_dependency_graph_json_path: Path
    validation_readiness_dashboard_json_path: Path
    artifact_lineage_report_json_path: Path
    news_validation_gap_analysis_json_path: Path
    news_transformer_readiness_json_path: Path
    news_transformer_training_plan_json_path: Path
    catastrophic_news_audit_json_path: Path
    catastrophic_news_candidates_csv_path: Path
    catastrophic_news_veto_report_json_path: Path
    catastrophic_veto_candidate_attribution_json_path: Path
    catastrophic_veto_trade_attribution_csv_path: Path
    catastrophic_veto_strategy_comparison_json_path: Path
    catastrophic_veto_policy_json_path: Path
    catastrophic_veto_filtered_strategy_report_json_path: Path
    catastrophic_veto_removed_trades_csv_path: Path
    catastrophic_veto_removed_symbols_csv_path: Path
    catastrophic_veto_full_replay_report_json_path: Path
    catastrophic_veto_full_replay_trade_ledger_csv_path: Path
    catastrophic_veto_full_replay_equity_csv_path: Path
    catastrophic_veto_filtered_candidates_csv_path: Path
    catastrophic_veto_blocked_candidates_csv_path: Path
    catastrophic_veto_replay_seam_report_json_path: Path
    catastrophic_veto_bounceback_report_json_path: Path
    catastrophic_veto_bounceback_by_category_csv_path: Path
    catastrophic_veto_bounceback_examples_csv_path: Path
    catastrophic_veto_extreme_only_policy_proposal_json_path: Path
    catastrophic_veto_policy_variant_comparison_json_path: Path
    catastrophic_veto_policy_variant_counts_csv_path: Path
    catastrophic_veto_policy_variant_metrics_csv_path: Path
    catastrophic_veto_policy_variant_removed_trades_csv_path: Path
    catastrophic_veto_policy_variant_bounceback_csv_path: Path
    catastrophic_veto_policy_frontier_report_json_path: Path
    catastrophic_veto_policy_frontier_csv_path: Path
    catastrophic_veto_policy_variant_examples_csv_path: Path
    catastrophic_veto_loser_bounceback_casebook_json_path: Path
    catastrophic_veto_loser_bounceback_cases_csv_path: Path
    catastrophic_veto_loser_bounceback_feature_diff_csv_path: Path
    catastrophic_veto_loser_bounceback_keyword_diff_csv_path: Path
    catastrophic_veto_taxonomy_improvement_plan_json_path: Path
    catastrophic_veto_parked_status_json_path: Path
    catastrophic_news_evidence_quality_report_json_path: Path
    catastrophic_news_evidence_quality_by_field_csv_path: Path
    catastrophic_news_evidence_quality_by_symbol_csv_path: Path
    catastrophic_veto_policy_mode_comparison_json_path: Path
    catastrophic_veto_policy_mode_counts_csv_path: Path
    news_evidence_lineage_report_json_path: Path
    news_evidence_lineage_by_stage_csv_path: Path
    news_evidence_missing_field_examples_csv_path: Path
    news_evidence_readiness_report_json_path: Path
    news_event_taxonomy_report_json_path: Path
    news_event_taxonomy_counts_csv_path: Path
    news_event_taxonomy_examples_csv_path: Path
    news_duplicate_grouping_report_json_path: Path
    news_duplicate_grouping_examples_csv_path: Path
    news_point_in_time_text_safety_report_json_path: Path
    news_point_in_time_text_safety_examples_csv_path: Path
    news_text_keyword_baseline_report_json_path: Path
    news_text_keyword_baseline_scores_csv_path: Path
    walk_forward_validation_report_json_path: Path
    walk_forward_fold_results_csv_path: Path
    placebo_permutation_report_json_path: Path
    placebo_permutation_results_csv_path: Path
    exposure_matched_controls_json_path: Path
    trade_count_matched_controls_json_path: Path
    concentration_fragility_report_json_path: Path
    shadow_csv_path: Path
    manifest_json_path: Path
    markdown_path: Path


_PATH_FILENAMES = {
    "dataset_csv_path": "stock_alpha_news_risk_overlay_dataset.csv",
    "coverage_json_path": "coverage_report.json",
    "leakage_json_path": "leakage_report.json",
    "metrics_json_path": "logistic_regression_metrics.json",
    "portfolio_json_path": "price_vs_news_portfolio_report.json",
    "accounting_json_path": "accounting_definitions.json",
    "accounting_audit_json_path": "accounting_audit.json",
    "equity_curve_csv_path": "equity_curve.csv",
    "drawdown_curve_csv_path": "drawdown_curve.csv",
    "trade_ledger_csv_path": "trade_ledger.csv",
    "daily_equity_price_only_csv_path": "daily_equity_price_only.csv",
    "daily_equity_news_cash_csv_path": "daily_equity_news_cash.csv",
    "daily_equity_news_replacement_csv_path": "daily_equity_news_replacement.csv",
    "daily_equity_news_reduced_size_csv_path": "daily_equity_news_reduced_size.csv",
    "open_trade_portfolio_json_path": "portfolio_comparison.json",
    "replay_risk_metrics_json_path": "risk_metrics.json",
    "action_attribution_json_path": "action_attribution.json",
    "score_direction_audit_json_path": "score_direction_audit.json",
    "news_score_deciles_csv_path": "news_score_deciles.csv",
    "corrected_news_score_deciles_csv_path": "corrected_news_score_deciles.csv",
    "decile_join_audit_json_path": "decile_join_audit.json",
    "decile_trade_reconciliation_json_path": "decile_trade_reconciliation.json",
    "news_score_direction_report_json_path": "news_score_direction_report.json",
    "news_score_direction_summary_md_path": "news_score_direction_summary.md",
    "replay_action_attribution_json_path": "replay_action_attribution.json",
    "event_category_analysis_json_path": "event_category_analysis.json",
    "contrarian_strategy_comparison_json_path": "contrarian_strategy_comparison.json",
    "contrarian_trade_ledger_csv_path": "contrarian_trade_ledger.csv",
    "price_stabilisation_comparison_json_path": "price_stabilisation_comparison.json",
    "resilience_filter_analysis_json_path": "resilience_filter_analysis.json",
    "extreme_event_archive_csv_path": "extreme_event_archive.csv",
    "extreme_event_memory_report_json_path": "extreme_event_memory_report.json",
    "cost_scenario_comparison_json_path": "cost_scenario_comparison.json",
    "chronological_split_manifest_json_path": "chronological_split_manifest.json",
    "experiment_registry_jsonl_path": "experiment_registry.jsonl",
    "contrarian_grid_results_csv_path": "contrarian_grid_results.csv",
    "contrarian_grid_selection_json_path": "contrarian_grid_selection.json",
    "contrarian_fold_results_csv_path": "contrarian_fold_results.csv",
    "contrarian_parameter_stability_json_path": "contrarian_parameter_stability.json",
    "contrarian_frozen_config_json_path": "contrarian_frozen_config.json",
    "contrarian_holdout_report_json_path": "contrarian_holdout_report.json",
    "contrarian_holdout_trade_ledger_csv_path": "contrarian_holdout_trade_ledger.csv",
    "contrarian_holdout_equity_csv_path": "contrarian_holdout_equity.csv",
    "contrarian_holdout_comparison_md_path": "contrarian_holdout_comparison.md",
    "contrarian_walk_forward_folds_csv_path": "contrarian_walk_forward_folds.csv",
    "contrarian_walk_forward_summary_json_path": "contrarian_walk_forward_summary.json",
    "contrarian_chronological_validation_plan_json_path": "contrarian_chronological_validation_plan.json",
    "contrarian_chronological_periods_csv_path": "contrarian_chronological_periods.csv",
    "contrarian_walk_forward_validation_report_json_path": "contrarian_walk_forward_validation_report.json",
    "contrarian_placebo_permutation_report_json_path": "contrarian_placebo_permutation_report.json",
    "contrarian_placebo_permutation_results_csv_path": "contrarian_placebo_permutation_results.csv",
    "contrarian_matched_control_report_json_path": "contrarian_matched_control_report.json",
    "contrarian_matched_control_results_csv_path": "contrarian_matched_control_results.csv",
    "contrarian_profit_concentration_report_json_path": "contrarian_profit_concentration_report.json",
    "contrarian_trade_fragility_by_symbol_csv_path": "contrarian_trade_fragility_by_symbol.csv",
    "contrarian_trade_fragility_by_year_csv_path": "contrarian_trade_fragility_by_year.csv",
    "contrarian_top_trade_removal_csv_path": "contrarian_top_trade_removal.csv",
    "contrarian_year_regime_report_json_path": "contrarian_year_regime_report.json",
    "contrarian_year_regime_results_csv_path": "contrarian_year_regime_results.csv",
    "contrarian_year_regime_examples_csv_path": "contrarian_year_regime_examples.csv",
    "contrarian_symbol_year_ablation_report_json_path": "contrarian_symbol_year_ablation_report.json",
    "contrarian_without_top_symbols_csv_path": "contrarian_without_top_symbols.csv",
    "contrarian_without_top_years_csv_path": "contrarian_without_top_years.csv",
    "contrarian_cost_slippage_robustness_report_json_path": "contrarian_cost_slippage_robustness_report.json",
    "contrarian_cost_slippage_robustness_csv_path": "contrarian_cost_slippage_robustness.csv",
    "contrarian_data_validity_audit_json_path": "contrarian_data_validity_audit.json",
    "intraday_5min_expansion_plan_json_path": "intraday_5min_expansion_plan.json",
    "contrarian_placebo_results_csv_path": "contrarian_placebo_results.csv",
    "contrarian_placebo_summary_json_path": "contrarian_placebo_summary.json",
    "contrarian_matched_controls_json_path": "contrarian_matched_controls.json",
    "contrarian_contribution_by_year_csv_path": "contrarian_contribution_by_year.csv",
    "contrarian_contribution_by_symbol_csv_path": "contrarian_contribution_by_symbol.csv",
    "contrarian_concentration_report_json_path": "contrarian_concentration_report.json",
    "universe_survivorship_audit_json_path": "universe_survivorship_audit.json",
    "universe_membership_by_date_csv_path": "universe_membership_by_date.csv",
    "corporate_action_audit_json_path": "corporate_action_audit.json",
    "missing_news_bias_report_json_path": "missing_news_bias_report.json",
    "covered_vs_uncovered_candidates_csv_path": "covered_vs_uncovered_candidates.csv",
    "text_model_readiness_json_path": "text_model_readiness.json",
    "validation_stage_placeholders_json_path": "validation_stage_placeholders.json",
    "parallel_execution_report_json_path": "parallel_execution_report.json",
    "replay_assumptions_json_path": "replay_assumptions.json",
    "replay_data_audit_json_path": "replay_data_audit.json",
    "artifact_manifest_json_path": "artifact_manifest.json",
    "artifact_validation_report_json_path": "artifact_validation_report.json",
    "news_validation_workflow_map_json_path": "news_validation_workflow_map.json",
    "validation_dependency_graph_json_path": "validation_dependency_graph.json",
    "validation_readiness_dashboard_json_path": "validation_readiness_dashboard.json",
    "artifact_lineage_report_json_path": "artifact_lineage_report.json",
    "news_validation_gap_analysis_json_path": "news_validation_gap_analysis.json",
    "news_transformer_readiness_json_path": "news_transformer_readiness.json",
    "news_transformer_training_plan_json_path": "news_transformer_training_plan.json",
    "catastrophic_news_audit_json_path": "catastrophic_news_audit.json",
    "catastrophic_news_candidates_csv_path": "catastrophic_news_candidates.csv",
    "catastrophic_news_veto_report_json_path": "catastrophic_news_veto_report.json",
    "catastrophic_veto_candidate_attribution_json_path": "catastrophic_veto_candidate_attribution.json",
    "catastrophic_veto_trade_attribution_csv_path": "catastrophic_veto_trade_attribution.csv",
    "catastrophic_veto_strategy_comparison_json_path": "catastrophic_veto_strategy_comparison.json",
    "catastrophic_veto_policy_json_path": "catastrophic_veto_policy.json",
    "catastrophic_veto_filtered_strategy_report_json_path": "catastrophic_veto_filtered_strategy_report.json",
    "catastrophic_veto_removed_trades_csv_path": "catastrophic_veto_removed_trades.csv",
    "catastrophic_veto_removed_symbols_csv_path": "catastrophic_veto_removed_symbols.csv",
    "catastrophic_veto_full_replay_report_json_path": "catastrophic_veto_full_replay_report.json",
    "catastrophic_veto_full_replay_trade_ledger_csv_path": "catastrophic_veto_full_replay_trade_ledger.csv",
    "catastrophic_veto_full_replay_equity_csv_path": "catastrophic_veto_full_replay_equity.csv",
    "catastrophic_veto_filtered_candidates_csv_path": "catastrophic_veto_filtered_candidates.csv",
    "catastrophic_veto_blocked_candidates_csv_path": "catastrophic_veto_blocked_candidates.csv",
    "catastrophic_veto_replay_seam_report_json_path": "catastrophic_veto_replay_seam_report.json",
    "catastrophic_veto_bounceback_report_json_path": "catastrophic_veto_bounceback_report.json",
    "catastrophic_veto_bounceback_by_category_csv_path": "catastrophic_veto_bounceback_by_category.csv",
    "catastrophic_veto_bounceback_examples_csv_path": "catastrophic_veto_bounceback_examples.csv",
    "catastrophic_veto_extreme_only_policy_proposal_json_path": "catastrophic_veto_extreme_only_policy_proposal.json",
    "catastrophic_veto_policy_variant_comparison_json_path": "catastrophic_veto_policy_variant_comparison.json",
    "catastrophic_veto_policy_variant_counts_csv_path": "catastrophic_veto_policy_variant_counts.csv",
    "catastrophic_veto_policy_variant_metrics_csv_path": "catastrophic_veto_policy_variant_metrics.csv",
    "catastrophic_veto_policy_variant_removed_trades_csv_path": "catastrophic_veto_policy_variant_removed_trades.csv",
    "catastrophic_veto_policy_variant_bounceback_csv_path": "catastrophic_veto_policy_variant_bounceback.csv",
    "catastrophic_veto_policy_frontier_report_json_path": "catastrophic_veto_policy_frontier_report.json",
    "catastrophic_veto_policy_frontier_csv_path": "catastrophic_veto_policy_frontier.csv",
    "catastrophic_veto_policy_variant_examples_csv_path": "catastrophic_veto_policy_variant_examples.csv",
    "catastrophic_veto_loser_bounceback_casebook_json_path": "catastrophic_veto_loser_bounceback_casebook.json",
    "catastrophic_veto_loser_bounceback_cases_csv_path": "catastrophic_veto_loser_bounceback_cases.csv",
    "catastrophic_veto_loser_bounceback_feature_diff_csv_path": "catastrophic_veto_loser_bounceback_feature_diff.csv",
    "catastrophic_veto_loser_bounceback_keyword_diff_csv_path": "catastrophic_veto_loser_bounceback_keyword_diff.csv",
    "catastrophic_veto_taxonomy_improvement_plan_json_path": "catastrophic_veto_taxonomy_improvement_plan.json",
    "catastrophic_veto_parked_status_json_path": "catastrophic_veto_parked_status.json",
    "catastrophic_news_evidence_quality_report_json_path": "catastrophic_news_evidence_quality_report.json",
    "catastrophic_news_evidence_quality_by_field_csv_path": "catastrophic_news_evidence_quality_by_field.csv",
    "catastrophic_news_evidence_quality_by_symbol_csv_path": "catastrophic_news_evidence_quality_by_symbol.csv",
    "catastrophic_veto_policy_mode_comparison_json_path": "catastrophic_veto_policy_mode_comparison.json",
    "catastrophic_veto_policy_mode_counts_csv_path": "catastrophic_veto_policy_mode_counts.csv",
    "news_evidence_lineage_report_json_path": "news_evidence_lineage_report.json",
    "news_evidence_lineage_by_stage_csv_path": "news_evidence_lineage_by_stage.csv",
    "news_evidence_missing_field_examples_csv_path": "news_evidence_missing_field_examples.csv",
    "news_evidence_readiness_report_json_path": "news_evidence_readiness_report.json",
    "news_event_taxonomy_report_json_path": "news_event_taxonomy_report.json",
    "news_event_taxonomy_counts_csv_path": "news_event_taxonomy_counts.csv",
    "news_event_taxonomy_examples_csv_path": "news_event_taxonomy_examples.csv",
    "news_duplicate_grouping_report_json_path": "news_duplicate_grouping_report.json",
    "news_duplicate_grouping_examples_csv_path": "news_duplicate_grouping_examples.csv",
    "news_point_in_time_text_safety_report_json_path": "news_point_in_time_text_safety_report.json",
    "news_point_in_time_text_safety_examples_csv_path": "news_point_in_time_text_safety_examples.csv",
    "news_text_keyword_baseline_report_json_path": "news_text_keyword_baseline_report.json",
    "news_text_keyword_baseline_scores_csv_path": "news_text_keyword_baseline_scores.csv",
    "walk_forward_validation_report_json_path": "walk_forward_validation_report.json",
    "walk_forward_fold_results_csv_path": "walk_forward_fold_results.csv",
    "placebo_permutation_report_json_path": "placebo_permutation_report.json",
    "placebo_permutation_results_csv_path": "placebo_permutation_results.csv",
    "exposure_matched_controls_json_path": "exposure_matched_controls.json",
    "trade_count_matched_controls_json_path": "trade_count_matched_controls.json",
    "concentration_fragility_report_json_path": "concentration_fragility_report.json",
    "shadow_csv_path": "shadow_decision_log.csv",
    "manifest_json_path": "model_manifest.json",
    "markdown_path": "README.md",
}


def build_news_risk_research_paths(output_dir: Path) -> NewsRiskResearchPaths:
    kwargs = {"output_dir": output_dir}
    kwargs.update({
        field_name: output_dir / filename
        for field_name, filename in _PATH_FILENAMES.items()
    })
    return NewsRiskResearchPaths(**kwargs)
