"""News-source research helpers."""

from core.research.ml.stock_level.news_sources.catastrophic_events import (
    CATASTROPHIC_NEWS_TAXONOMY,
    catastrophic_news_taxonomy_report,
    classify_catastrophic_news_event,
    classify_catastrophic_news_rows,
)
from core.research.ml.stock_level.news_sources.providers import (
    PROVIDER_METADATA,
    SEC_CIK_BY_SYMBOL,
    SEC_COMPANY_TICKERS_URL,
    AlphaVantageNewsSource,
    AlpacaBenzingaNewsSource,
    CompanyPressReleaseRssSource,
    FinnhubNewsSource,
    FmpNewsSource,
    GdeltNewsSource,
    MassiveStockNewsSource,
    NewsApiNewsSource,
    NewsSource,
    ProviderRateLimitError,
    SecCompanyFilingsSource,
    SecEdgarNewsSource,
    default_news_sources,
    gdelt_query_terms,
    normalize_sec_company_tickers,
    normalize_sec_ticker,
    sec_submissions_url,
    standard_library_json_get,
    standard_library_text_get,
)
from core.research.ml.stock_level.news_sources.registry import (
    NEWS_SOURCE_CLASSIFICATIONS,
    NEWS_SOURCE_PLANNING_SCHEMA_VERSION,
    load_validated_rss_registry,
    news_source_planning_registry,
    reconcile_news_source_registry,
)

__all__ = [
    "PROVIDER_METADATA",
    "SEC_CIK_BY_SYMBOL",
    "SEC_COMPANY_TICKERS_URL",
    "AlphaVantageNewsSource",
    "AlpacaBenzingaNewsSource",
    "CATASTROPHIC_NEWS_TAXONOMY",
    "CompanyPressReleaseRssSource",
    "FinnhubNewsSource",
    "FmpNewsSource",
    "GdeltNewsSource",
    "MassiveStockNewsSource",
    "NEWS_SOURCE_CLASSIFICATIONS",
    "NEWS_SOURCE_PLANNING_SCHEMA_VERSION",
    "NewsApiNewsSource",
    "NewsSource",
    "ProviderRateLimitError",
    "SecCompanyFilingsSource",
    "SecEdgarNewsSource",
    "catastrophic_news_taxonomy_report",
    "classify_catastrophic_news_event",
    "classify_catastrophic_news_rows",
    "default_news_sources",
    "gdelt_query_terms",
    "load_validated_rss_registry",
    "news_source_planning_registry",
    "reconcile_news_source_registry",
    "normalize_sec_company_tickers",
    "normalize_sec_ticker",
    "sec_submissions_url",
    "standard_library_json_get",
    "standard_library_text_get",
]
