DUAL_MOMENTUM_DEFAULTS = {
        "symbols": [
            "AAPL",
            "MSFT",
            "NVDA",
            "META",
            "GOOGL",
            "AMZN",
            "TSLA",
            "SPY",
            "QQQ",
        ],
        "stock_symbols": [
            "AAPL",
            "MSFT",
            "NVDA",
            "META",
            "GOOGL",
            "AMZN",
            "TSLA",
            "AVGO",
            "AMD",
            "CRM",
            "ORCL",
            "ADBE",
            "NFLX",
            "COST",
            "JPM",
            "V",
            "MA",
            "HD",
            "UNH",
            "LLY",
            "XOM",
            "CVX",
            "CAT",
            "DE",
            "GE",
            "NOW",
            "PANW",
            "WMT",
            "PG",
            "KO",
            "PEP",
            "MCD",
            "NKE",
            "DIS",
            "CMCSA",
            "TMO",
            "ABT",
            "MRK",
            "PFE",
            "ABBV",
            "JNJ",
            "BAC",
            "GS",
            "MS",
            "BLK",
            "SCHW",
            "TXN",
            "QCOM",
            "INTU",
            "IBM",
            "AMAT",
            "LRCX",
            "MU",
            "HON",
            "UPS",
            "LOW",
            "RTX",
            "LMT",
            "BA",
            "COP",
            "SLB",
            "EOG",
            "NEE",
            "DUK",
            "SO",
            "PLD",
            "AMT",
            "SPY",
            "QQQ",
        ],
        "etf_symbols": [
            "XLK",
            "XLY",
            "XLF",
            "XLI",
            "XLV",
            "XLE",
            "XLU",
            "XLP",
            "XLB",
            "VNQ",
            "TLT",
            "GLD",
            "SPY",
            "QQQ",
        ],
        "top_n": 5,
        "momentum_periods": [63, 126],
        "regime_symbol": "SPY",
        "regime_sma_period": 200,
        "use_asset_trend_filter": True,
        "asset_sma_period": 200,
        "selection_mode": "all_positive",
        "min_selection_score": 0.03,
        "max_selected_assets": 5,
        "weighting": "inverse_volatility",
        "max_position_weight": 0.35,
        "weight_volatility_lookback": 63,
        "rebalance_frequency": "monthly",
        "target_exposure": 1.0,
        "target_volatility": None,
        "volatility_lookback": 63,
        "max_drawdown_guard": 0.20,
        "drawdown_guard_cooldown": 1,
        "strict_drawdown_kill_switch": True,
        "risk_off_symbols": [],
        "risk_off_top_n": 1,
        "risk_off_momentum_periods": [63, 126],
        "risk_regime_mode": "scaled",
        "mixed_risk_exposure": 0.75,
        "risk_off_risk_exposure": 0.25,
        "fast_reentry_enabled": True,
        "fast_reentry_symbols": [],
        "fast_reentry_sma_period": 100,
        "fast_reentry_momentum_period": 63,
        "fast_reentry_breadth_percent": 0.60,
        "fallback_symbols": ["SPY", "QQQ"],
        "fallback_allocation": 0.0,
        "fallback_min_risk_assets": 3,
        "fallback_momentum_periods": [63, 126],
        "decay_exit_enabled": False,
        "decay_momentum_period": 63,
        "rank_drop_exit_top_n": None,
        "chop_filter_enabled": True,
        "chop_lookback": 63,
        "min_chop_momentum": 0.02,
        "chop_risk_exposure": 0.50,
        "quality_filter_enabled": False,
        "quality_momentum_period": 21,
        "quality_sma_period": 50,
        "quality_require_momentum_improving": False,
        "cooldown_enabled": False,
        "cooldown_periods": 2,
        "cooldown_loss_threshold": -0.03,
        "rank_hysteresis_enabled": False,
        "rank_hysteresis_margin": 2,
        "rank_hysteresis_max_rank": None,
        "max_rebalance_replacements": None,
        "replacement_score_gap": 0.0,
        "rebalance_min_trade_weight": 0.0,
        "leadership_filter_enabled": False,
        "leadership_symbol": "SPY",
        "leadership_momentum_periods": [21, 63],
        "benchmark_sleeve_symbols": ["SPY", "QQQ"],
        "benchmark_sleeve_allocation": 0.0,
        "benchmark_sleeve_momentum_periods": [63],
        "benchmark_sleeve_top_n": 1,
        "benchmark_participation_filter_enabled": False,
        "benchmark_participation_period": 63,
        "benchmark_participation_min_return": 0.03,
        "benchmark_participation_max_selected_excess": 0.0,
        "sector_map": {},
        "max_sector_weight": None,
        "ranking_score_mode": "average_momentum",
        "enhanced_momentum_periods": [21, 63, 126],
        "enhanced_momentum_weights": [0.20, 0.35, 0.45],
        "relative_strength_symbol": "SPY",
        "relative_strength_periods": [21, 63],
        "relative_strength_weight": 0.25,
        "volatility_penalty_weight": 0.05,
        "ranking_volatility_lookback": 63,
        "min_breadth_percent": 0.60,
        "benchmark_symbol": "SPY",
        "transaction_cost_bps": 2.0,
        "experiment_grid": {
            "top_n": [5],
            "min_selection_score": [0.03],
            "max_selected_assets": [5],
            "rebalance_frequency": ["monthly"],
            "momentum_periods": [[63, 126]],
            "use_asset_trend_filter": [True],
            "selection_mode": ["all_positive"],
            "weighting": ["equal", "inverse_volatility"],
            "max_position_weight": [0.25, 0.35],
            "min_breadth_percent": [0.60],
            "target_volatility": [None],
            "max_drawdown_guard": [0.20],
            "strict_drawdown_kill_switch": [True],
            "mixed_risk_exposure": [0.75],
            "risk_off_risk_exposure": [0.25],
            "fallback_allocation": [0.0],
            "decay_exit_enabled": [False],
            "rank_drop_exit_top_n": [None],
            "chop_filter_enabled": [True],
            "chop_risk_exposure": [0.50, 0.60],
            "quality_filter_enabled": [False],
            "quality_require_momentum_improving": [False],
            "cooldown_enabled": [False],
            "rank_hysteresis_enabled": [False],
            "rank_hysteresis_margin": [2],
            "rank_hysteresis_max_rank": [None],
            "max_rebalance_replacements": [None],
            "replacement_score_gap": [0.0],
            "rebalance_min_trade_weight": [0.0],
            "leadership_filter_enabled": [False, True],
            "benchmark_sleeve_allocation": [0.0, 0.10, 0.15, 0.20, 0.25],
            "benchmark_participation_filter_enabled": [False],
            "max_sector_weight": [None],
            "ranking_score_mode": ["average_momentum", "enhanced"],
            "transaction_cost_bps": [2.0],
            "commission_bps": [0.0],
            "slippage_bps": [0.0],
            "spread_cost_bps": [0.0],
        },
        "risk_regime_experiments": [
            {
                "name": "baseline_inverse_vol",
                "overrides": {
                    "risk_off_symbols": [],
                    "risk_regime_mode": "binary",
                    "risk_off_risk_exposure": 0.0,
                    "fast_reentry_enabled": False,
                },
            },
            {
                "name": "cash_risk_off",
                "overrides": {
                    "risk_off_symbols": [],
                    "risk_regime_mode": "binary",
                    "risk_off_risk_exposure": 0.0,
                    "fast_reentry_enabled": False,
                },
            },
            {
                "name": "defensive_assets",
                "overrides": {
                    "risk_off_symbols": [
                        "BIL",
                        "SHY",
                        "IEF",
                        "TLT",
                        "GLD",
                    ],
                    "risk_regime_mode": "binary",
                    "risk_off_risk_exposure": 0.0,
                    "fast_reentry_enabled": False,
                },
            },
            {
                "name": "scaled_exposure",
                "overrides": {
                    "risk_off_symbols": [],
                    "risk_regime_mode": "scaled",
                    "risk_off_risk_exposure": 0.25,
                    "fast_reentry_enabled": False,
                },
            },
            {
                "name": "fast_reentry",
                "overrides": {
                    "risk_off_symbols": [],
                    "risk_regime_mode": "binary",
                    "fast_reentry_enabled": True,
                },
            },
            {
                "name": "scaled_plus_fast_reentry",
                "overrides": {
                    "risk_off_symbols": [],
                    "risk_regime_mode": "scaled",
                    "mixed_risk_exposure": 0.50,
                    "risk_off_risk_exposure": 0.25,
                    "fast_reentry_enabled": True,
                },
            },
            {
                "name": "scaled_fast_reentry_75",
                "overrides": {
                    "risk_off_symbols": [],
                    "risk_regime_mode": "scaled",
                    "mixed_risk_exposure": 0.75,
                    "risk_off_risk_exposure": 0.25,
                    "fast_reentry_enabled": True,
                },
            },
            {
                "name": "scaled_fast_reentry_fallback",
                "overrides": {
                    "risk_off_symbols": [],
                    "risk_regime_mode": "scaled",
                    "mixed_risk_exposure": 0.75,
                    "risk_off_risk_exposure": 0.25,
                    "fast_reentry_enabled": True,
                    "fallback_symbols": ["SPY", "QQQ"],
                    "fallback_allocation": 0.25,
                    "fallback_min_risk_assets": 3,
                },
            },
            {
                "name": "scaled_fast_reentry_decay",
                "overrides": {
                    "risk_off_symbols": [],
                    "risk_regime_mode": "scaled",
                    "mixed_risk_exposure": 0.75,
                    "risk_off_risk_exposure": 0.25,
                    "fast_reentry_enabled": True,
                    "decay_exit_enabled": True,
                    "decay_momentum_period": 63,
                    "rank_drop_exit_top_n": 7,
                },
            },
            {
                "name": "scaled_fast_reentry_chop",
                "overrides": {
                    "risk_off_symbols": [],
                    "risk_regime_mode": "scaled",
                    "mixed_risk_exposure": 0.75,
                    "risk_off_risk_exposure": 0.25,
                    "fast_reentry_enabled": True,
                    "chop_filter_enabled": True,
                    "chop_lookback": 63,
                    "min_chop_momentum": 0.02,
                    "chop_risk_exposure": 0.50,
                },
            },
            {
                "name": "ranked_top3_enhanced_chop",
                "overrides": {
                    "selection_mode": "ranked",
                    "top_n": 3,
                    "min_selection_score": 0.03,
                    "max_selected_assets": 3,
                    "ranking_score_mode": "enhanced",
                    "risk_off_symbols": [],
                    "risk_regime_mode": "scaled",
                    "mixed_risk_exposure": 0.75,
                    "risk_off_risk_exposure": 0.25,
                    "fast_reentry_enabled": True,
                    "chop_filter_enabled": True,
                    "chop_risk_exposure": 0.50,
                },
            },
            {
                "name": "ranked_top5_enhanced_chop",
                "overrides": {
                    "selection_mode": "ranked",
                    "top_n": 5,
                    "min_selection_score": 0.03,
                    "max_selected_assets": 5,
                    "ranking_score_mode": "enhanced",
                    "risk_off_symbols": [],
                    "risk_regime_mode": "scaled",
                    "mixed_risk_exposure": 0.75,
                    "risk_off_risk_exposure": 0.25,
                    "fast_reentry_enabled": True,
                    "chop_filter_enabled": True,
                    "chop_risk_exposure": 0.50,
                },
            },
            {
                "name": "ranked_top7_enhanced_chop",
                "overrides": {
                    "selection_mode": "ranked",
                    "top_n": 7,
                    "min_selection_score": 0.03,
                    "max_selected_assets": 7,
                    "ranking_score_mode": "enhanced",
                    "risk_off_symbols": [],
                    "risk_regime_mode": "scaled",
                    "mixed_risk_exposure": 0.75,
                    "risk_off_risk_exposure": 0.25,
                    "fast_reentry_enabled": True,
                    "chop_filter_enabled": True,
                    "chop_risk_exposure": 0.50,
                },
            },
            {
                "name": "scaled_chop_60",
                "overrides": {
                    "risk_off_symbols": [],
                    "risk_regime_mode": "scaled",
                    "mixed_risk_exposure": 0.75,
                    "risk_off_risk_exposure": 0.25,
                    "fast_reentry_enabled": True,
                    "chop_filter_enabled": True,
                    "chop_risk_exposure": 0.60,
                },
            },
            {
                "name": "scaled_chop_70",
                "overrides": {
                    "risk_off_symbols": [],
                    "risk_regime_mode": "scaled",
                    "mixed_risk_exposure": 0.75,
                    "risk_off_risk_exposure": 0.25,
                    "fast_reentry_enabled": True,
                    "chop_filter_enabled": True,
                    "chop_risk_exposure": 0.70,
                },
            },
            {
                "name": "scaled_chop_75",
                "overrides": {
                    "risk_off_symbols": [],
                    "risk_regime_mode": "scaled",
                    "mixed_risk_exposure": 0.75,
                    "risk_off_risk_exposure": 0.25,
                    "fast_reentry_enabled": True,
                    "chop_filter_enabled": True,
                    "chop_risk_exposure": 0.75,
                },
            },
            {
                "name": "fast_reentry_50",
                "overrides": {
                    "risk_off_symbols": [],
                    "risk_regime_mode": "scaled",
                    "mixed_risk_exposure": 0.75,
                    "risk_off_risk_exposure": 0.25,
                    "fast_reentry_enabled": True,
                    "fast_reentry_sma_period": 50,
                    "chop_filter_enabled": True,
                },
            },
            {
                "name": "fast_reentry_spy_qqq_50",
                "overrides": {
                    "risk_off_symbols": [],
                    "risk_regime_mode": "scaled",
                    "mixed_risk_exposure": 0.75,
                    "risk_off_risk_exposure": 0.25,
                    "fast_reentry_enabled": True,
                    "fast_reentry_symbols": ["SPY", "QQQ"],
                    "fast_reentry_sma_period": 50,
                    "chop_filter_enabled": True,
                },
            },
            {
                "name": "chop_benchmark_sleeve_20",
                "overrides": {
                    "risk_off_symbols": [],
                    "risk_regime_mode": "scaled",
                    "mixed_risk_exposure": 0.75,
                    "risk_off_risk_exposure": 0.25,
                    "fast_reentry_enabled": True,
                    "chop_filter_enabled": True,
                    "benchmark_sleeve_symbols": ["SPY", "QQQ"],
                    "benchmark_sleeve_allocation": 0.20,
                },
            },
            {
                "name": "chop_leadership_filter",
                "overrides": {
                    "risk_off_symbols": [],
                    "risk_regime_mode": "scaled",
                    "mixed_risk_exposure": 0.75,
                    "risk_off_risk_exposure": 0.25,
                    "fast_reentry_enabled": True,
                    "chop_filter_enabled": True,
                    "leadership_filter_enabled": True,
                    "leadership_symbol": "SPY",
                    "leadership_momentum_periods": [21, 63],
                },
            },
            {
                "name": "scaled_reentry_chop_quality",
                "overrides": {
                    "risk_off_symbols": [],
                    "risk_regime_mode": "scaled",
                    "mixed_risk_exposure": 0.75,
                    "risk_off_risk_exposure": 0.25,
                    "fast_reentry_enabled": True,
                    "chop_filter_enabled": True,
                    "quality_filter_enabled": True,
                    "quality_require_momentum_improving": True,
                    "cooldown_enabled": False,
                },
            },
            {
                "name": "scaled_reentry_chop_quality_cooldown",
                "overrides": {
                    "risk_off_symbols": [],
                    "risk_regime_mode": "scaled",
                    "mixed_risk_exposure": 0.75,
                    "risk_off_risk_exposure": 0.25,
                    "fast_reentry_enabled": True,
                    "chop_filter_enabled": True,
                    "quality_filter_enabled": True,
                    "quality_require_momentum_improving": True,
                    "cooldown_enabled": True,
                    "cooldown_periods": 2,
                    "cooldown_loss_threshold": -0.03,
                },
            },
        ],
    }
