MULTI_STRATEGY_DEFAULTS = {
        "symbols": [
            "AAPL",
            "MSFT",
            "NVDA",
            "META",
            "GOOGL",
            "AMZN",
            "TSLA",
            "SPY",
            "QQQ",
            "BIL",
            "SHY",
            "IEF",
            "TLT",
            "GLD",
        ],
        "benchmark_symbol": "SPY",
        "warmup_days": 500,
        "sleeves": [
            {
                "name": "dual_momentum",
                "enabled": True,
                "weight": 0.70,
                "parameters": {
                    "top_n": 5,
                    "momentum_periods": [63, 126],
                    "regime_symbol": "SPY",
                    "regime_sma_period": 200,
                    "use_asset_trend_filter": True,
                    "asset_sma_period": 200,
                    "selection_mode": "all_positive",
                    "weighting": "equal",
                    "max_position_weight": 0.25,
                    "rebalance_frequency": "monthly",
                    "target_exposure": 1.0,
                    "target_volatility": 0.20,
                    "volatility_lookback": 63,
                    "max_drawdown_guard": 0.20,
                    "drawdown_guard_cooldown": 1,
                    "strict_drawdown_kill_switch": True,
                    "risk_off_symbols": [],
                    "risk_off_top_n": 1,
                    "risk_off_momentum_periods": [63, 126],
                    "risk_regime_mode": "scaled",
                    "mixed_risk_exposure": 0.75,
                    "risk_off_risk_exposure": 0.25,
                    "fast_reentry_enabled": True,
                    "fast_reentry_symbols": [],
                    "fast_reentry_sma_period": 100,
                    "fast_reentry_momentum_period": 63,
                    "fast_reentry_breadth_percent": 0.60,
                    "fallback_symbols": ["SPY", "QQQ"],
                    "fallback_allocation": 0.0,
                    "fallback_min_risk_assets": 3,
                    "fallback_momentum_periods": [63, 126],
                    "decay_exit_enabled": False,
                    "decay_momentum_period": 63,
                    "rank_drop_exit_top_n": None,
                    "chop_filter_enabled": True,
                    "chop_lookback": 63,
                    "min_chop_momentum": 0.02,
                    "chop_risk_exposure": 0.50,
                    "quality_filter_enabled": False,
                    "quality_momentum_period": 21,
                    "quality_sma_period": 50,
                    "quality_require_momentum_improving": False,
                    "cooldown_enabled": False,
                    "cooldown_periods": 2,
                    "cooldown_loss_threshold": -0.03,
                    "leadership_filter_enabled": False,
                    "leadership_symbol": "SPY",
                    "leadership_momentum_periods": [21, 63],
                    "benchmark_sleeve_symbols": ["SPY", "QQQ"],
                    "benchmark_sleeve_allocation": 0.0,
                    "benchmark_sleeve_momentum_periods": [63],
                    "benchmark_sleeve_top_n": 1,
                    "min_breadth_percent": 0.60,
                    "benchmark_symbol": "SPY",
                    "transaction_cost_bps": 2.0,
                },
            },
            {
                "name": "relative_strength",
                "enabled": True,
                "weight": 0.30,
                "parameters": {
                    "symbols": [
                        "AAPL",
                        "MSFT",
                        "NVDA",
                        "META",
                        "GOOGL",
                        "AMZN",
                        "TSLA",
                        "SPY",
                        "QQQ",
                    ],
                    "top_n": 3,
                    "momentum_periods": [63, 126],
                    "sma_period": 200,
                    "rebalance_frequency": "monthly",
                    "target_exposure": 1.0,
                    "benchmark_symbol": "SPY",
                    "transaction_cost_bps": 2.0,
                },
            },
        ],
        "experiment_grid": {
            "sleeve_weights": [
                [1.0, 0.0],
                [0.7, 0.3],
                [0.5, 0.5],
                [0.3, 0.7],
                [0.0, 1.0],
            ],
        },
    }
