import yaml


DEFAULT_CONFIG = {
    "strategy": {
        "rsi_period": 14,
        "rsi_oversold": 30,
        "rsi_overbought": 70,
    },
    "position_sizing": {
        "mode": "fixed_fractional",
        "target_exposure": 0.20,
        "max_exposure": 0.20,
    },
    "research": {
        "optimization_metric": "composite",
        "report_top_n": 10,
        "parallel_workers": 1,
        "parallel_mode": "thread",
        "two_stage_enabled": True,
        "two_stage_top_n": 5,
        "stage_one_max_combinations": 80,
        "early_stop_max_drawdown": 0.30,
        "early_stop_equity_floor_pct": 0.70,
        "optimizer_min_closed_trades": 1,
        "min_closed_trades": 20,
        "min_profit_factor": 1.1,
        "min_sharpe": 0,
        "max_drawdown": 0.20,
        "min_time_in_market": 0.02,
        "max_time_in_market": 0.95,
        "require_positive_excess": True,
        "require_sharpe_edge": True,
        "relative_strength": {
            "symbols": [
                "AAPL",
                "MSFT",
                "NVDA",
                "META",
                "GOOGL",
                "AMZN",
                "TSLA",
                "SPY",
                "QQQ",
                "BIL",
                "SHY",
                "IEF",
                "TLT",
                "GLD",
            ],
            "top_n": 2,
            "momentum_periods": [63, 126],
            "sma_period": 200,
            "rebalance_frequency": "monthly",
            "target_exposure": 1.0,
            "benchmark_symbol": "SPY",
            "transaction_cost_bps": 2.0,
            "experiment_grid": {
                "top_n": [1, 2, 3],
                "rebalance_frequency": ["monthly", "weekly"],
                "momentum_periods": [[21, 63], [63, 126], [126, 252]],
            },
        },
        "dual_momentum": {
            "symbols": [
                "AAPL",
                "MSFT",
                "NVDA",
                "META",
                "GOOGL",
                "AMZN",
                "TSLA",
                "SPY",
                "QQQ",
            ],
            "etf_symbols": [
                "XLK",
                "XLY",
                "XLF",
                "XLI",
                "XLV",
                "XLE",
                "XLU",
                "XLP",
                "XLB",
                "VNQ",
                "TLT",
                "GLD",
                "SPY",
                "QQQ",
            ],
            "top_n": 5,
            "momentum_periods": [63, 126],
            "regime_symbol": "SPY",
            "regime_sma_period": 200,
            "use_asset_trend_filter": True,
            "asset_sma_period": 200,
            "selection_mode": "all_positive",
            "weighting": "inverse_volatility",
            "max_position_weight": 0.35,
            "weight_volatility_lookback": 63,
            "rebalance_frequency": "monthly",
            "target_exposure": 1.0,
            "target_volatility": None,
            "volatility_lookback": 63,
            "max_drawdown_guard": 0.20,
            "drawdown_guard_cooldown": 1,
            "strict_drawdown_kill_switch": True,
            "risk_off_symbols": [],
            "risk_off_top_n": 1,
            "risk_off_momentum_periods": [63, 126],
            "risk_regime_mode": "scaled",
            "mixed_risk_exposure": 0.50,
            "risk_off_risk_exposure": 0.25,
            "fast_reentry_enabled": True,
            "fast_reentry_sma_period": 100,
            "fast_reentry_momentum_period": 63,
            "fast_reentry_breadth_percent": 0.60,
            "min_breadth_percent": 0.60,
            "benchmark_symbol": "SPY",
            "transaction_cost_bps": 2.0,
            "experiment_grid": {
                "top_n": [5, 7],
                "rebalance_frequency": ["monthly"],
                "momentum_periods": [[63, 126]],
                "use_asset_trend_filter": [True],
                "selection_mode": ["ranked", "all_positive"],
                "weighting": ["equal", "inverse_volatility"],
                "max_position_weight": [0.25, 0.35],
                "min_breadth_percent": [0.40, 0.50, 0.60],
                "target_volatility": [None, 0.20],
                "max_drawdown_guard": [0.20],
                "strict_drawdown_kill_switch": [False, True],
            },
            "risk_regime_experiments": [
                {
                    "name": "baseline_inverse_vol",
                    "overrides": {
                        "risk_off_symbols": [],
                        "risk_regime_mode": "binary",
                        "risk_off_risk_exposure": 0.0,
                        "fast_reentry_enabled": False,
                    },
                },
                {
                    "name": "cash_risk_off",
                    "overrides": {
                        "risk_off_symbols": [],
                        "risk_regime_mode": "binary",
                        "risk_off_risk_exposure": 0.0,
                        "fast_reentry_enabled": False,
                    },
                },
                {
                    "name": "defensive_assets",
                    "overrides": {
                        "risk_off_symbols": [
                            "BIL",
                            "SHY",
                            "IEF",
                            "TLT",
                            "GLD",
                        ],
                        "risk_regime_mode": "binary",
                        "risk_off_risk_exposure": 0.0,
                        "fast_reentry_enabled": False,
                    },
                },
                {
                    "name": "scaled_exposure",
                    "overrides": {
                        "risk_off_symbols": [],
                        "risk_regime_mode": "scaled",
                        "risk_off_risk_exposure": 0.25,
                        "fast_reentry_enabled": False,
                    },
                },
                {
                    "name": "fast_reentry",
                    "overrides": {
                        "risk_off_symbols": [],
                        "risk_regime_mode": "binary",
                        "fast_reentry_enabled": True,
                    },
                },
                {
                    "name": "scaled_plus_fast_reentry",
                    "overrides": {
                        "risk_off_symbols": [],
                        "risk_regime_mode": "scaled",
                        "mixed_risk_exposure": 0.50,
                        "risk_off_risk_exposure": 0.25,
                        "fast_reentry_enabled": True,
                    },
                },
            ],
        },
        "multi_strategy": {
            "symbols": [
                "AAPL",
                "MSFT",
                "NVDA",
                "META",
                "GOOGL",
                "AMZN",
                "TSLA",
                "SPY",
                "QQQ",
                "BIL",
                "SHY",
                "IEF",
                "TLT",
                "GLD",
            ],
            "benchmark_symbol": "SPY",
            "warmup_days": 500,
            "sleeves": [
                {
                    "name": "dual_momentum",
                    "enabled": True,
                    "weight": 0.70,
                    "parameters": {
                        "top_n": 5,
                        "momentum_periods": [63, 126],
                        "regime_symbol": "SPY",
                        "regime_sma_period": 200,
                        "use_asset_trend_filter": True,
                        "asset_sma_period": 200,
                        "selection_mode": "all_positive",
                        "weighting": "equal",
                        "max_position_weight": 0.25,
                        "rebalance_frequency": "monthly",
                        "target_exposure": 1.0,
                        "target_volatility": 0.20,
                        "volatility_lookback": 63,
                        "max_drawdown_guard": 0.20,
                        "drawdown_guard_cooldown": 1,
                        "strict_drawdown_kill_switch": True,
                        "risk_off_symbols": [],
                        "risk_off_top_n": 1,
                        "risk_off_momentum_periods": [63, 126],
                        "risk_regime_mode": "scaled",
                        "mixed_risk_exposure": 0.50,
                        "risk_off_risk_exposure": 0.25,
                        "fast_reentry_enabled": True,
                        "fast_reentry_sma_period": 100,
                        "fast_reentry_momentum_period": 63,
                        "fast_reentry_breadth_percent": 0.60,
                        "min_breadth_percent": 0.60,
                        "benchmark_symbol": "SPY",
                        "transaction_cost_bps": 2.0,
                    },
                },
                {
                    "name": "relative_strength",
                    "enabled": True,
                    "weight": 0.30,
                    "parameters": {
                        "symbols": [
                            "AAPL",
                            "MSFT",
                            "NVDA",
                            "META",
                            "GOOGL",
                            "AMZN",
                            "TSLA",
                            "SPY",
                            "QQQ",
                        ],
                        "top_n": 3,
                        "momentum_periods": [63, 126],
                        "sma_period": 200,
                        "rebalance_frequency": "monthly",
                        "target_exposure": 1.0,
                        "benchmark_symbol": "SPY",
                        "transaction_cost_bps": 2.0,
                    },
                },
            ],
            "experiment_grid": {
                "sleeve_weights": [
                    [1.0, 0.0],
                    [0.7, 0.3],
                    [0.5, 0.5],
                    [0.3, 0.7],
                    [0.0, 1.0],
                ],
            },
        },
        "fast_mode": {
            "symbols": ["AAPL", "SPY"],
            "relative_strength_symbols": ["AAPL", "SPY"],
            "dual_momentum_symbols": ["AAPL", "SPY"],
            "multi_strategy_symbols": ["AAPL", "SPY"],
            "years": 2,
            "strategies": [
                "trend_pullback",
                "ema_rsi_pullback",
                "ensemble_vote",
                "buy_and_hold",
            ],
            "max_grid_values_per_parameter": 1,
            "stage_one_max_combinations": 12,
            "two_stage_top_n": 2,
            "min_closed_trades": 5,
            "optimizer_min_closed_trades": 1,
            "walk_forward_folds": [
                {
                    "train_start": "2024-07-01",
                    "train_end": "2025-06-30",
                    "test_start": "2025-07-01",
                    "test_end": "2026-06-15",
                },
            ],
        },
        "parameter_grid": {
            "ema_fast_period": [20, 40, 50, 60, 100],
            "ema_slow_period": [50, 180, 200, 220, 300],
            "atr_stop_multiplier": [1.0, 2.0, 3.0],
            "trailing_atr_multiplier": [2.0, 3.0],
            "atr_take_profit_multiplier": [2.0, 3.0, 4.0],
            "target_exposure": [0.10, 0.20, 0.30, 0.40, 0.60],
        },
        "walk_forward_folds": [
            {
                "train_start": "2021-01-01",
                "train_end": "2023-12-31",
                "test_start": "2024-01-01",
                "test_end": "2024-12-31",
            },
            {
                "train_start": "2022-01-01",
                "train_end": "2024-12-31",
                "test_start": "2025-01-01",
                "test_end": "2025-12-31",
            },
            {
                "train_start": "2023-01-01",
                "train_end": "2025-12-31",
                "test_start": "2026-01-01",
                "test_end": "2026-12-31",
            },
        ],
        "strategy_comparison": [
            {
                "name": "ema_crossover",
                "parameter_grid": {
                    "ema_fast_period": [20, 40, 50, 60],
                    "ema_slow_period": [50, 180, 200, 220],
                    "atr_stop_multiplier": [1.0, 2.0],
                    "atr_take_profit_multiplier": [3.0, 4.0],
                    "target_exposure": [0.10, 0.20, 0.30, 0.40, 0.60],
                },
            },
            {
                "name": "ema_rsi_filter",
                "parameter_grid": {
                    "ema_fast_period": [20, 40],
                    "ema_slow_period": [50, 180],
                    "rsi_entry": [50, 55],
                    "rsi_exit": [40, 45],
                    "atr_stop_multiplier": [1.0, 2.0],
                    "atr_take_profit_multiplier": [3.0],
                    "target_exposure": [0.10, 0.20, 0.30, 0.40, 0.60],
                },
            },
            {
                "name": "rsi_mean_reversion",
                "parameter_grid": {
                    "rsi_oversold": [30, 35, 40, 45],
                    "rsi_exit_level": [50, 55, 60, 65],
                    "atr_stop_multiplier": [1.0, 2.0],
                    "atr_take_profit_multiplier": [2.0, 3.0],
                    "target_exposure": [0.10, 0.20, 0.30, 0.40, 0.60],
                },
            },
            {
                "name": "donchian_breakout",
                "parameter_grid": {
                    "donchian_lookback": [5, 10, 20, 55],
                    "atr_stop_multiplier": [2.0, 3.0],
                    "atr_take_profit_multiplier": [3.0, 4.0],
                    "target_exposure": [0.10, 0.20, 0.30, 0.40, 0.60],
                },
            },
            {
                "name": "trend_pullback",
                "parameter_grid": {
                    "pullback_fast_period": [20, 50],
                    "pullback_tolerance": [0.01, 0.02, 0.04],
                    "pullback_exit_extension": [0.04, 0.08],
                    "use_regime_filter": [True, False],
                    "atr_stop_multiplier": [1.0, 2.0],
                    "atr_take_profit_multiplier": [2.0, 3.0],
                    "target_exposure": [0.20, 0.40, 0.60],
                },
            },
            {
                "name": "ensemble_vote",
                "parameter_grid": {
                    "ensemble_min_buy_votes": [2, 3],
                    "ensemble_min_sell_votes": [1, 2],
                    "rsi_entry": [50, 55],
                    "rsi_exit": [40, 45],
                    "rsi_pullback": [40, 45],
                    "pullback_tolerance": [0.02, 0.04],
                    "use_regime_filter": [True],
                    "use_breakout_vote": [True, False],
                    "atr_stop_multiplier": [1.5, 2.0],
                    "trailing_atr_multiplier": [2.0, 3.0],
                    "atr_take_profit_multiplier": [6.0, None],
                    "target_exposure": [0.40],
                },
            },
            {
                "name": "buy_and_hold",
                "parameter_grid": {
                    "target_exposure": [1.0],
                    "position_max_exposure": [1.0],
                },
            },
        ],
    },
    "reports": {
        "backtest_dir": "reports/backtests",
        "walk_forward_dir": "reports/walk_forward",
        "summary_dir": "reports/summary",
    },
    "cache": {
        "enabled": True,
        "data_dir": "cache/data",
        "results_dir": "cache/results",
    },
}


def merge_defaults(defaults, values):
    merged = defaults.copy()

    for key, value in (values or {}).items():
        if (
            isinstance(value, dict)
            and isinstance(merged.get(key), dict)
        ):
            merged[key] = merge_defaults(merged[key], value)
        else:
            merged[key] = value

    return merged


def load_config(path="config/config.yaml"):
    with open(path, "r") as f:
        loaded = yaml.safe_load(f)

    return merge_defaults(DEFAULT_CONFIG, loaded)
