ML_DEFAULTS = {
    "enabled": False,
    "mode": "research",
    "research_years": 10,
    "minimum_history_years": 9,
    "history_coverage_tolerance_days": 10,
    "smoke_test_minimum_history_years": 5,
    "allow_short_history_for_smoke_test": False,
    "research_label": "VALIDATED_9Y_RESEARCH_CURRENT_SURVIVOR_UNIVERSE",
    "smoke_test_output_dir": "reports/ml/smoke_test",
    "smoke_test_cache_dir": "cache/ml/smoke_test",
    "historical_data_provider": "stooq_parquet",
    "stooq_csv_dir": "data/raw/stooq",
    "stooq_bulk_extracted_dir": "data/raw/stooq_bulk/extracted",
    "stooq_bulk_zip_path": "data/raw/stooq_bulk/us_daily_ascii.zip",
    "stooq_parquet_dir": "data/processed/stooq_parquet",
    "parquet_dir": "data/processed/stooq_parquet",
    "inventory_output_dir": "reports/ml",
    "universe_output_dir": "data/reference/universes",
    "min_history_years": 9,
    "max_latest_gap_days": 14,
    "min_average_dollar_volume_252d": 50_000_000,
    "expanded_rebalance_audit_path": "reports/ml/expanded_rebalance_dataset_audit.json",
    "expanded_rebalance_dataset": {
        "rebalance_frequencies": ["monthly", "biweekly", "weekly"],
        "top_n_values": [3, 5, 7],
        "weightings": ["equal", "inverse_volatility"],
        "universe_paths": [
            "data/reference/universes/current_32.yaml",
            "data/reference/universes/us_liquid_100.yaml",
        ],
        "reduce_drawdown_threshold": 0.08,
        "reduce_excess_return_threshold": -0.01,
        "reduce_volatility_adjusted_threshold": -0.10,
    },
    "sector_reference_path": "data/reference/sector_by_symbol.json",
    "sector_by_symbol": {},
    "calibration_bin_count": 10,
    "rolling_base_rate_lookback_samples": 252,
    "ranking_quantile_count": 5,
    "prediction_target": "champion_success",
    "model_type": "logistic_regression",
    "feature_set": "price_regime_v1",
    "label_type": "champion_success",
    "train_start": None,
    "train_end": None,
    "test_start": None,
    "test_end": None,
    "prediction_horizon": 42,
    "label_horizon_days": 42,
    "drawdown_risk_threshold": 0.08,
    "decision_threshold": 0.50,
    "class_weight_balanced": True,
    "comparison_models": ["logistic_regression", "random_forest", "gradient_boosting"],
    "shadow_model_type": "gradient_boosting",
    "shadow_thresholds": [0.10, 0.15, 0.20, 0.25],
    "shadow_reduced_exposures": [0.70, 0.80, 0.90],
    "shadow_transaction_cost_bps": 5.0,
    "shadow_holdout_threshold": 0.20,
    "shadow_holdout_reduced_exposure": 0.70,
    "include_champion_state_features": True,
    "test_fraction": 0.20,
    "walk_forward_folds": 3,
    "random_seed": 42,
    "output_dir": "reports/ml",
    "num_workers": 1,
    "model_threads": 1,
    "torch_num_threads": 1,
    "sklearn_n_jobs": 1,
    "numpy_num_threads": 1,
    "stock_alpha_feature_n_jobs": 4,
    "stock_ranker_model_n_jobs": 4,
    "stock_alpha_overnight_stage_n_jobs": 1,
    "stock_ranker_target_column": "actual_forward_return_10d",
    "stock_ranker_market_symbol": "SPY",
    "stock_alpha_dev_required_symbols": ["SPY"],
    "stock_ranker_target_comparison_enabled": True,
    "stock_ranker_target_columns": [
        "actual_forward_return_10d",
        "actual_market_residual_return_10d",
        "actual_vol_adjusted_forward_return_10d",
        "actual_rank_normalized_forward_return_10d",
    ],
    "stock_alpha_overnight_run_attribution": False,
    "stock_alpha_run_size": "benchmark",
    "stock_alpha_dev_max_dates": 80,
    "stock_alpha_dev_max_symbols": 120,
    "stock_alpha_dev_recent_dates_only": True,
    "stock_alpha_resume_existing_outputs": True,
    "stock_alpha_force_refresh": False,
    "stock_target_comparison_n_jobs": 4,
    "stock_feature_attribution_max_models": 4,
    "stock_feature_attribution_max_features": 12,
    "stock_feature_attribution_permutation_repeats": 1,
    "stock_portfolio_replay_enabled": True,
    "stock_portfolio_replay_top_n": 25,
    "stock_portfolio_replay_top_decile": True,
    "stock_portfolio_replay_cost_bps": 10,
    "stock_portfolio_replay_slippage_bps": 5,
    "stock_portfolio_replay_max_position_weight": 0.05,
    "stock_portfolio_replay_min_position_weight": 0.0,
    "stock_portfolio_replay_rebalance_frequency": "existing_rebalance_dates",
    "stock_portfolio_replay_allow_short": False,
    "stock_portfolio_replay_signal_columns": [
        "stock_level_predicted_forward_return_10d_elastic_net",
        "stock_level_predicted_forward_return_10d_random_forest",
        "predicted_momentum_120d",
    ],
    "stock_alpha_overnight_run_portfolio_replay": True,
    "stock_portfolio_policy_sweep_enabled": True,
    "stock_portfolio_policy_sweep_n_jobs": 4,
    "stock_portfolio_policy_sweep_signals": ["stock_level_predicted_forward_return_10d_elastic_net", "stock_level_predicted_forward_return_10d_random_forest", "predicted_momentum_120d"],
    "stock_portfolio_policy_sweep_top_n_values": [10, 25, 50],
    "stock_portfolio_policy_sweep_max_position_weights": [0.03, 0.05, 0.10],
    "stock_portfolio_policy_sweep_cost_bps_values": [5, 10, 25],
    "stock_portfolio_policy_sweep_slippage_bps_values": [5],
    "stock_portfolio_policy_sweep_turnover_caps": [None, 0.50, 1.00],
    "stock_portfolio_policy_sweep_volatility_targets": [None, 0.10, 0.15],
    "stock_portfolio_policy_sweep_allow_short": False,
    "stock_portfolio_policy_sweep_max_configs_dev": 40,
    "stock_portfolio_policy_sweep_max_configs_benchmark": 250,
    "stock_portfolio_policy_sweep_max_configs_full": 1000,
    "stock_alpha_experiment_report_enabled": True,
    "stock_alpha_experiment_report_max_age_hours": 24,
    "stock_alpha_experiment_report_require_all_outputs": False,
    "stock_alpha_experiment_registry_path": "reports/ml/stock_alpha_experiment_registry.csv",
    "stock_alpha_report_root": "reports/ml/benchmark/regime_transformer_meta_ensemble_v1/stock_alpha",
    "stock_alpha_allow_legacy_output_paths": False,
    "stock_alpha_experiment_report_level": "dev_smoke",
    "feature_workers": 1,
    "benchmark_symbols": ["SPY", "QQQ"],
    "feature_lookback_days": 252,
    "sequence_length": 63,
    "transformer_d_model": 32,
    "transformer_heads": 4,
    "transformer_layers": 2,
    "transformer_feedforward": 64,
    "transformer_dropout": 0.10,
    "transformer_epochs": 20,
    "transformer_batch_size": 32,
    "transformer_learning_rate": 0.001,
    "transformer_weight_decay": 0.0001,
    "transformer_device": "cpu",
    "dlinear_sequence_length": 126,
    "dlinear_epochs": 50,
    "dlinear_batch_size": 32,
    "dlinear_learning_rate": 0.001,
    "dlinear_weight_decay": 0.001,
    "dlinear_device": "cpu",
    "dlinear_pos_weight": "auto",
    "patchtst_sequence_length": 126,
    "patchtst_patch_length": 16,
    "patchtst_patch_stride": 8,
    "patchtst_d_model": 64,
    "patchtst_heads": 4,
    "patchtst_layers": 2,
    "patchtst_feedforward": 128,
    "patchtst_dropout": 0.10,
    "patchtst_epochs": 30,
    "patchtst_batch_size": 32,
    "patchtst_learning_rate": 0.001,
    "patchtst_weight_decay": 0.0001,
    "patchtst_device": "cpu",
    "patchtst_pos_weight": "auto",
    "itransformer_sequence_length": 126,
    "itransformer_d_model": 64,
    "itransformer_heads": 4,
    "itransformer_layers": 2,
    "itransformer_feedforward": 128,
    "itransformer_dropout": 0.10,
    "itransformer_epochs": 30,
    "itransformer_batch_size": 32,
    "itransformer_learning_rate": 0.001,
    "itransformer_weight_decay": 0.0001,
    "itransformer_device": "cpu",
    "itransformer_pos_weight": "auto",
    "momentum_transformer_sequence_length": 126,
    "momentum_transformer_d_model": 64,
    "momentum_transformer_heads": 4,
    "momentum_transformer_layers": 2,
    "momentum_transformer_feedforward": 128,
    "momentum_transformer_dropout": 0.10,
    "momentum_transformer_epochs": 30,
    "momentum_transformer_batch_size": 32,
    "momentum_transformer_learning_rate": 0.001,
    "momentum_transformer_weight_decay": 0.0001,
    "momentum_transformer_device": "cpu",
    "momentum_transformer_pos_weight": "auto",
    "momentum_transformer_size_multiplier_floor": 0.25,
    "momentum_transformer_size_multiplier_ceiling": 1.25,
    "multitask_enabled": False,
    "multitask_primary_target": "should_reduce_exposure",
    "multitask_regression_targets": [
        "forward_return_5d",
        "forward_return_10d",
        "future_volatility",
        "future_drawdown",
        "max_adverse_excursion",
        "max_favourable_excursion",
    ],
    "multitask_classification_weight": 1.0,
    "multitask_regression_loss": "huber",
    "multitask_huber_delta": 1.0,
    "multitask_forward_return_5d_weight": 0.20,
    "multitask_forward_return_10d_weight": 0.20,
    "multitask_future_volatility_weight": 0.15,
    "multitask_future_drawdown_weight": 0.20,
    "multitask_max_adverse_excursion_weight": 0.15,
    "multitask_max_favourable_excursion_weight": 0.10,
    "multitask_transformer_sequence_length": 63,
    "multitask_transformer_d_model": 32,
    "multitask_transformer_heads": 4,
    "multitask_transformer_layers": 2,
    "multitask_transformer_feedforward": 64,
    "multitask_transformer_dropout": 0.10,
    "multitask_transformer_epochs": 20,
    "multitask_transformer_batch_size": 32,
    "multitask_transformer_learning_rate": 0.001,
    "multitask_transformer_weight_decay": 0.0001,
    "multitask_transformer_device": "cpu",
    "market_context_sequence_length": 63,
    "market_context_hidden_size": 32,
    "market_context_epochs": 20,
    "market_context_batch_size": 32,
    "market_context_learning_rate": 0.001,
    "market_context_weight_decay": 0.0001,
    "market_context_dropout": 0.10,
    "market_context_device": "cpu",
    "market_context_risk_multiplier_floor": 0.25,
    "market_context_risk_multiplier_ceiling": 1.25,
    "sentiment_features_enabled": False,
    "sentiment_feature_version": "sentiment_v1",
    "sentiment_min_reliability_tier": 2,
    "sentiment_lookback_windows": [1, 5, 10, 21],
    "sentiment_require_first_seen_timestamp": True,
    "news_transformer_sequence_length": 63,
    "news_transformer_d_model": 32,
    "news_transformer_heads": 4,
    "news_transformer_layers": 1,
    "news_transformer_feedforward": 64,
    "news_transformer_dropout": 0.10,
    "news_transformer_epochs": 20,
    "news_transformer_batch_size": 32,
    "news_transformer_learning_rate": 0.001,
    "news_transformer_weight_decay": 0.0001,
    "news_transformer_device": "cpu",
    "tft_encoder_length": 64,
    "tft_prediction_horizons": [5, 10],
    "tft_hidden_size": 64,
    "tft_attention_heads": 4,
    "tft_lstm_layers": 1,
    "tft_dropout": 0.15,
    "tft_epochs": 30,
    "tft_batch_size": 64,
    "tft_learning_rate": 0.001,
    "tft_weight_decay": 0.0005,
    "tft_device": "cpu",
    "tft_known_future_features": [
        "day_of_week",
        "month",
        "is_month_end",
        "rebalance_frequency",
        "days_until_next_rebalance",
    ],
}
