FAST_MODE_DEFAULTS = {'symbols': ['AAPL', 'SPY'],
 'relative_strength_symbols': ['AAPL', 'SPY'],
 'dual_momentum_symbols': ['AAPL', 'SPY'],
 'multi_strategy_symbols': ['AAPL', 'SPY'],
 'years': 2,
 'strategies': ['trend_pullback', 'ema_rsi_pullback', 'ensemble_vote', 'buy_and_hold'],
 'max_grid_values_per_parameter': 1,
 'stage_one_max_combinations': 12,
 'two_stage_top_n': 2,
 'min_closed_trades': 5,
 'optimizer_min_closed_trades': 1,
 'walk_forward_folds': [{'train_start': '2024-07-01',
                         'train_end': '2025-06-30',
                         'test_start': '2025-07-01',
                         'test_end': '2026-06-15'}]}

PARAMETER_GRID_DEFAULTS = {'ema_fast_period': [20, 40, 50, 60, 100],
 'ema_slow_period': [50, 180, 200, 220, 300],
 'atr_stop_multiplier': [1.0, 2.0, 3.0],
 'trailing_atr_multiplier': [2.0, 3.0],
 'atr_take_profit_multiplier': [2.0, 3.0, 4.0],
 'target_exposure': [0.1, 0.2, 0.3, 0.4, 0.6]}

WALK_FORWARD_FOLDS_DEFAULTS = [{'train_start': '2021-01-01',
  'train_end': '2023-12-31',
  'test_start': '2024-01-01',
  'test_end': '2024-12-31'},
 {'train_start': '2022-01-01',
  'train_end': '2024-12-31',
  'test_start': '2025-01-01',
  'test_end': '2025-12-31'},
 {'train_start': '2023-01-01',
  'train_end': '2025-12-31',
  'test_start': '2026-01-01',
  'test_end': '2026-12-31'}]

STRATEGY_COMPARISON_DEFAULTS = [{'name': 'ema_crossover',
  'parameter_grid': {'ema_fast_period': [20, 40, 50, 60],
                     'ema_slow_period': [50, 180, 200, 220],
                     'atr_stop_multiplier': [1.0, 2.0],
                     'atr_take_profit_multiplier': [3.0, 4.0],
                     'target_exposure': [0.1, 0.2, 0.3, 0.4, 0.6]}},
 {'name': 'ema_rsi_filter',
  'parameter_grid': {'ema_fast_period': [20, 40],
                     'ema_slow_period': [50, 180],
                     'rsi_entry': [50, 55],
                     'rsi_exit': [40, 45],
                     'atr_stop_multiplier': [1.0, 2.0],
                     'atr_take_profit_multiplier': [3.0],
                     'target_exposure': [0.1, 0.2, 0.3, 0.4, 0.6]}},
 {'name': 'rsi_mean_reversion',
  'parameter_grid': {'rsi_oversold': [30, 35, 40, 45],
                     'rsi_exit_level': [50, 55, 60, 65],
                     'atr_stop_multiplier': [1.0, 2.0],
                     'atr_take_profit_multiplier': [2.0, 3.0],
                     'target_exposure': [0.1, 0.2, 0.3, 0.4, 0.6]}},
 {'name': 'donchian_breakout',
  'parameter_grid': {'donchian_lookback': [5, 10, 20, 55],
                     'atr_stop_multiplier': [2.0, 3.0],
                     'atr_take_profit_multiplier': [3.0, 4.0],
                     'target_exposure': [0.1, 0.2, 0.3, 0.4, 0.6]}},
 {'name': 'trend_pullback',
  'parameter_grid': {'pullback_fast_period': [20, 50],
                     'pullback_tolerance': [0.01, 0.02, 0.04],
                     'pullback_exit_extension': [0.04, 0.08],
                     'use_regime_filter': [True, False],
                     'atr_stop_multiplier': [1.0, 2.0],
                     'atr_take_profit_multiplier': [2.0, 3.0],
                     'target_exposure': [0.2, 0.4, 0.6]}},
 {'name': 'ensemble_vote',
  'parameter_grid': {'ensemble_min_buy_votes': [2, 3],
                     'ensemble_min_sell_votes': [1, 2],
                     'rsi_entry': [50, 55],
                     'rsi_exit': [40, 45],
                     'rsi_pullback': [40, 45],
                     'pullback_tolerance': [0.02, 0.04],
                     'use_regime_filter': [True],
                     'use_breakout_vote': [True, False],
                     'atr_stop_multiplier': [1.5, 2.0],
                     'trailing_atr_multiplier': [2.0, 3.0],
                     'atr_take_profit_multiplier': [6.0, None],
                     'target_exposure': [0.4]}},
 {'name': 'buy_and_hold',
  'parameter_grid': {'target_exposure': [1.0], 'position_max_exposure': [1.0]}}]
