RELATIVE_STRENGTH_DEFAULTS = {
        "symbols": [
            "AAPL",
            "MSFT",
            "NVDA",
            "META",
            "GOOGL",
            "AMZN",
            "TSLA",
            "SPY",
            "QQQ",
            "BIL",
            "SHY",
            "IEF",
            "TLT",
            "GLD",
        ],
        "top_n": 2,
        "momentum_periods": [63, 126],
        "sma_period": 200,
        "rebalance_frequency": "monthly",
        "target_exposure": 1.0,
        "benchmark_symbol": "SPY",
        "transaction_cost_bps": 2.0,
        "experiment_grid": {
            "top_n": [1, 2, 3],
            "rebalance_frequency": ["monthly", "weekly"],
            "momentum_periods": [[21, 63], [63, 126], [126, 252]],
        },
    }
